# Generated by Django 5.1.2 on 2024-10-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecorationFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Нет названия', max_length=100)),
                ('description', models.TextField(default='Нет описания')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Нет названия', max_length=100)),
                ('description', models.TextField(default='Нет описания')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='scotch',
            name='author',
        ),
        migrations.RemoveField(
            model_name='scotch',
            name='title',
        ),
        migrations.AddField(
            model_name='scotch',
            name='description',
            field=models.TextField(default='Нет описания'),
        ),
        migrations.AddField(
            model_name='scotch',
            name='name',
            field=models.CharField(default='Нет названия', max_length=100),
        ),
        migrations.AddField(
            model_name='scotch',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
