# Generated by Django 5.1.2 on 2024-10-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_decorationfilm_securityfilm_remove_scotch_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Нет названия', max_length=100)),
                ('description', models.TextField(default='Нет описания')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(default='default_image.jpg', upload_to='sun_films/')),
            ],
        ),
        migrations.DeleteModel(
            name='Scotch',
        ),
        migrations.AddField(
            model_name='decorationfilm',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='decoration_films/'),
        ),
        migrations.AddField(
            model_name='securityfilm',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='security_films/'),
        ),
    ]
