# Generated by Django 5.1.2 on 2024-11-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_sunfilm_delete_scotch_decorationfilm_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Нет названия', max_length=100)),
                ('description', models.TextField(default='Нет описания')),
                ('quantity', models.PositiveBigIntegerField(default='Нет в наличии')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(default='default_image.jpg', upload_to='sun_films/')),
            ],
        ),
        migrations.DeleteModel(
            name='DecorationFilm',
        ),
        migrations.DeleteModel(
            name='SecurityFilm',
        ),
        migrations.DeleteModel(
            name='SunFilm',
        ),
    ]
