# Generated by Django 5.1.2 on 2024-11-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_film_delete_decorationfilm_delete_securityfilm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.CharField(choices=[('sun', 'Sun Film'), ('security', 'Security Film'), ('decoration', 'Decoration Film')], default='sun', max_length=20),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='films/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
