# Generated by Django 5.1.2 on 2024-11-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_film_category_alter_film_image_alter_film_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(default='films/default_image.jpg', upload_to='films/'),
        ),
    ]
